spring:
  datasource:
    url: jdbc:sqlite:./timeblocks-dev.sqlite?busy_timeout=5000&journal_mode=WAL
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: com.timeblocks.sqlite.SQLiteDialect
        jdbc.time_zone: UTC
        format_sql: true
        highlight_sql: true
        type:
          descriptor:
            sql: trace  # show bound parameter values
  flyway:
    enabled: true
    locations: classpath:db/migration/sqlite
    baseline-on-migrate: true
    mixed: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.timeblocks: DEBUG

