spring:
  datasource:
    url: jdbc:sqlite:./timeblocks-dev.sqlite?busy_timeout=5000&journal_mode=WAL
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: com.timeblocks.sqlite.SQLiteDialect
        jdbc.time_zone: UTC
        format_sql: false
        highlight_sql: false
        type:
          descriptor:
            sql: info  # reduce bound parameter verbosity
  flyway:
    enabled: true
    locations: classpath:db/migration/common,classpath:db/migration/sqlite,classpath:db/migration/seed
    baseline-on-migrate: true
    mixed: true
    placeholders:
      seed_default_types: "0"
    ignore-missing-migrations: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: OFF
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: OFF
    org.springframework.jdbc.core: INFO
    org.springframework.transaction: INFO
    com.zaxxer.hikari: INFO
    com.timeblocks: INFO

